# reproducibleresearch

## Código para leer el conjunto de datos y/o procesar los datos
activity <- read_csv("C:/Users/anton/Downloads/repdata_data_activity/activity.csv")

# Histogram
hist(steps_by_day$total, main="Histogram of total number of steps per day", 
     xlab="Total number of steps in a day")
     
## Media y mediana del número de pasos dados cada día
mean 10766.19
median 10766.19

## Gráfico de series temporales del número medio de pasos dados
plot(steps_by_interval$interval, steps_by_interval$steps, type='l', 
     main="Average number of steps over all days", xlab="Interval", 
     ylab="Average number of steps")
     

## El intervalo de 5 minutos que, por término medio, contiene el número máximo de pasos
interval    steps
104      835 206.1698

## Código para describir y mostrar una estrategia para imputar los datos que faltan
#Imputing missing values
sum(is.na(activity))
2304
data_imputed <- activity
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value <- data_imputed$interval[i]
    steps_value <- steps_by_interval[
      steps_by_interval$interval == interval_value,]
    data_imputed$steps[i] <- steps_value$steps
  }


##Histograma del número total de pasos dados cada día después de imputar los valores que faltan
hist(df_imputed_steps_by_day$steps, main="Histogram of total number of steps per day imputed", 
     xlab="Total number of steps in a day")
     






## Todo el codigo
library(knitr)
library(dplyr)
library(ggplot2)

#Delete NA 
data <- activity[ with (activity, { !(is.na(steps)) } ), ]

#Total steps per day
by_day <- group_by(data, date)
steps_by_day <- summarise(by_day, total = sum(steps))
steps_by_day

#Histogram
hist(steps_by_day$total, main="Histogram of total number of steps per day", 
     xlab="Total number of steps in a day")

summary(steps_by_day)

#Average daily activity pattern
steps_by_interval <- aggregate(steps ~ interval, data, mean)

# create a time series plot 
plot(steps_by_interval$interval, steps_by_interval$steps, type='l', 
     main="Average number of steps over all days", xlab="Interval", 
     ylab="Average number of steps")

# find row with max of steps
max_steps_row <- which.max(steps_by_interval$steps)

# find interval with this max
steps_by_interval[max_steps_row, ]

#Imputing missing values
sum(is.na(activity))

data_imputed <- activity
for (i in 1:nrow(data_imputed)) {
  if (is.na(data_imputed$steps[i])) {
    interval_value <- data_imputed$interval[i]
    steps_value <- steps_by_interval[
      steps_by_interval$interval == interval_value,]
    data_imputed$steps[i] <- steps_value$steps
  }
}

# calculate  total number of steps taken each day
df_imputed_steps_by_day <- aggregate(steps ~ date, data_imputed, sum)
head(df_imputed_steps_by_day)

hist(df_imputed_steps_by_day$steps, main="Histogram of total number of steps per day imputed", 
     xlab="Total number of steps in a day")

# get mean and median of imputed data
mean(df_imputed_steps_by_day$steps)

median(df_imputed_steps_by_day$steps)

# get mean and median of data without NA's
mean(steps_by_day$total)

median(steps_by_day$total)

#Differences in activity patterns between weekdays and weekends
data_imputed['type_of_day'] <- weekdays(as.Date(data_imputed$date))
data_imputed$type_of_day[data_imputed$type_of_day  %in% c('Saturday','Sunday') ] <- "weekend"
data_imputed$type_of_day[data_imputed$type_of_day != "weekend"] <- "weekday"

# convert type_of_day from character to factor
data_imputed$type_of_day <- as.factor(data_imputed$type_of_day)

# calculate average steps by interval across all days
df_imputed_steps_by_interval <- aggregate(steps ~ interval + type_of_day, data_imputed, mean)

#Plot
qplot(interval, 
      steps, 
      data = df_imputed_steps_by_interval, 
      type = 'l', 
      geom=c("line"),
      xlab = "Interval", 
      ylab = "Number of steps", 
      main = "") +
  facet_wrap(~ type_of_day, ncol = 1)


